steps:
  - name: 'node:20-alpine'
    entrypoint: 'yarn'
    env: [ 'GH_PERSONAL_TOKEN=$_GH_PERSONAL_TOKEN' ]
    id: yarn Audit
    args: [ 'audit', '--groups', 'dependencies' ]
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: Docker Build NextJS
    waitFor:
      - yarn Audit
    args: [
      '--dockerfile=Dockerfile.nextjs',
      '--build-arg=GH_PERSONAL_TOKEN=$_GH_PERSONAL_TOKEN',
      '--destination=europe-west6-docker.pkg.dev/$PROJECT_ID/silenccio-docker-images/silenccio-b2b-fe-nextjs:latest',
      '--destination=europe-west6-docker.pkg.dev/$PROJECT_ID/silenccio-docker-images/silenccio-b2b-fe-nextjs:$SHORT_SHA',
      '--build-arg', 'NEXT_PUBLIC_API_URL=$_NEXT_PUBLIC_API_URL',
      '--build-arg', 'NEXT_PUBLIC_SITE_KEY=$_NEXT_PUBLIC_SITE_KEY',
      '--cache=$_KANIKO_USE_CACHE',
      '--cache-ttl=168h',
    ]
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: Docker Build Nginx
    waitFor:
      - yarn Audit
    args: [
      '--dockerfile=Dockerfile.nginx',
      '--build-arg=GH_PERSONAL_TOKEN=$_GH_PERSONAL_TOKEN',
      '--destination=europe-west6-docker.pkg.dev/$PROJECT_ID/silenccio-docker-images/silenccio-b2b-fe-nginx:latest',
      '--destination=europe-west6-docker.pkg.dev/$PROJECT_ID/silenccio-docker-images/silenccio-b2b-fe-nginx:$SHORT_SHA',
      '--cache=$_KANIKO_USE_CACHE',
      '--cache-ttl=168h',
    ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Cloud Run API Deploy
    waitFor:
      - Docker Build NextJS
      - Docker Build Nginx
    entrypoint: gcloud
    args: [
      'run',
      'services',
      'update',
      'silenccio-b2b-fe',
      '--region', '$_ZONE',
      '--container', 'nextjs',
      '--image', 'europe-west6-docker.pkg.dev/$PROJECT_ID/silenccio-docker-images/silenccio-b2b-fe-nextjs:$SHORT_SHA',
      '--container', 'nginx',
      '--image', 'europe-west6-docker.pkg.dev/$PROJECT_ID/silenccio-docker-images/silenccio-b2b-fe-nginx:$SHORT_SHA',
    ]
substitutions:
  _KANIKO_USE_CACHE: 'true'
