FROM node:20-alpine

WORKDIR /usr/app

COPY ./package*.json ./

RUN yarn install --production

COPY ./ ./

ARG NEXT_PUBLIC_API_URL

ARG NEXT_PUBLIC_SITE_KEY

RUN yarn run build

EXPOSE 3000

USER node

CMD [ "yarn", "start" ]